### ISSUE TITLE
A similar tool

### ISSUE THREAD

**Issue by stokito** [upnp-portmapper/upnp-port-mapper#3]
For Linux there is a similar open source UPnP GUI https://gitlab.gnome.org/DnaX/upnp-router-control
I hope it may be useful for you for inspiration.

**Comment by upnp-portmapper** [comment]
That's a good way to get banned stokito you piece trash, also your tool is trash you think you're smart you're a dumb clone trailer trash I take a shi in your moms vag where you were born! Cill yourself!!!
